### ISSUE TITLE
Could you provide an example in a flatlist can't seem to make it work on a flatlist

### ISSUE THREAD

**Issue by zRelux** [benawad/Picache#3]
I tried using this on a flatlist but it doesn't work I don't know why. If I put the link manually it works but if a put it threw code it doesn't render, could you provide and example on a flatlist? (I get the links on an api call and it works with normal image component).

**Comment by benawad** [comment]
https://github.com/benawad/Picache/tree/master/examples/flatlist-example

I tested it on iPhone X emulator
