### ISSUE TITLE
showing just part of the image when loaded for the fisrt time

### ISSUE THREAD

**Issue by gusmattos1** [benawad/Picache#4]
when I open  my app for the first time and it needs to download multiple images, (some with + 3mb)
when it renders, it shows only part of the images. The next time I run the app it works great.
this issue happens on Android and IOS 
![screenshot_20190111-162802_expo](https://user-images.githubusercontent.com/36457989/51060621-55dc9600-15be-11e9-94d6-6f7bc737588f.jpg)

**Comment by benawad** [comment]
I'm not sure what would cause that

**Comment by gusmattos1** [comment]
I didn't find the problem, but I made a workaround using a copy of your function downloadRemoteImage for the first time the app loads the picture :
`const shorthash = require("shorthash");

export const preCache = async (data) => {

    const result = data.map(async (item) => {
        let uri = item.image
        const name = shorthash.unique(uri);
        const path = `${Expo.FileSystem.cacheDirectory}${name}.png`;
        const image = await Expo.FileSystem.getInfoAsync(path);
        
        if (image.exists) {
            return null;
        }
        await Expo.FileSystem.downloadAsync(uri, path);
        return null;
    })

    const finished = await Promise.all(result)
    return finished
 }`

**Comment by ricardosaiz** [comment]
I have the same problem, what about this? any recommendations? 
Thank you
